apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery
  labels:
    app: celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: gcr.io/mathserv/math-serv
        command: ["celery"]
        args: ["-A","backend.celery_worker.celery","worker","--loglevel=info"]
        env:
        - name: STORAGE_PATH_BASE
          value: "/tmp"
        - name: DEBUG
          value: "True"
        - name: SECRET_KEY
          value: "blablabla"
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://math_serv:math_serv@postgresql/math_serv"
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          value: "False"
        - name: CELERY_BROKER_URL
          value: "amqp://math-serv:math-serv@rabbitmq:5672/math-serv"
        - name: RESULT_BACKEND
          value: "db+postgresql://math_serv:math_serv@db/math_serv"