"""empty message

Revision ID: 84772930cc26
Revises: 
Create Date: 2021-08-15 15:37:07.329632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84772930cc26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_type', sa.Enum('pow_op', 'fib_op', 'fact_op', name='operationtype'), nullable=False),
    sa.Column('operands', sa.JSON(), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operations')
    # ### end Alembic commands ###
